<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5312e77b-b73d-4221-bcc3-532e2b7d59fa</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Desktop\CodeAcademy\Mailing-master\Mailing-master\Mailing.csproj" />
    <ProjectReference Include="..\JobPortalProject.BL\JobPortalProject.BL.csproj" />
    <ProjectReference Include="..\JobPortalProject.DA\JobPortalProject.DA.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Portal\" />
  </ItemGroup>

</Project>
